name: hospitalappointments
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1
#version: 1.0.7+8
#version: 1.0.6+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
#  url_launcher: ^5.1.2
#  url_launcher: ^6.0.5
  url_launcher: ^5.4.10
  modal_progress_hud: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  #  datetime_picker_formfield: ^0.4.2
  validate: ^1.7.0
  flutter_html: ^0.10.4
  flutter_local_notifications: ^0.8.2
  flutter_typeahead: ^1.6.1
  font_awesome_flutter: ^8.5.0
  connectivity: ^0.4.4
  flutter_inappbrowser: ^1.2.1
  rflutter_alert: ^1.0.3
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_messaging: ^5.1.4
  shimmer: ^1.0.0
  cloud_firestore: ^0.12.9+2
  fcm_push: ^1.3.1
  material_design_icons_flutter: ^3.2.4096
  flutter_launcher_icons: ^0.7.2+1
  intl: ^0.16.0
  razorpay_flutter: ^1.2.5
  fluttertoast: ^8.0.7
  flutter_swiper: ^1.1.6
  in_app_update: ^1.1.10
  package_info: ^0.4.0+18

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logowhite.png
    - assets/banner.jpeg
    - assets/introscreen.png
    - assets/intrologo.png
    - assets/multispeciality_hospital.jpg
    - assets/find_doctor_icon.png
    - assets/ambulance_icon.png
    - assets/appointment_icon.png
    - assets/map_icon.png
    - assets/web_icon.png
    - assets/department.png
    - assets/app_background.png
    - assets/logo.png
    - assets/facebook_logo.png
    - assets/instagram_logo.png
    - assets/nursing_logo.png
    - assets/dr_selvaraja_director.jpg
    - assets/gunasekar_jmd.jpg
    - assets/sangeetha_priya.jpg
    - assets/sasikala_director.jpg
    - assets/milestone1.jpg
    - assets/milestone2.jpg
    - assets/milestone3.jpg
    - assets/milestone4.jpg
    - assets/milestone5.jpg
    - assets/milestone6.jpg
    - assets/milestone7.jpg
    - assets/milestone8.jpg
    - assets/milestone9.jpg
    - assets/milestone10.jpg
    - assets/milestone11.jpg
    - assets/milestone12.jpg
    - assets/dwc.jpg
    - assets/dharan_rock.jpg
    - assets/trust_founder.jpg
    - assets/paramedical_logo.png
    - assets/health_science.png
    - assets/logo-white.png
    - assets/bg.jpg
    - assets/icon/icon.png


  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages